name: gweezlebur.com
description: "Internet home of Michael D. Ivey since '99"
email: ivey@gweezlebur.com
url: https://gweezlebur.com
remote_theme: riggraz/no-style-please
collections:
  micro:
    output: true
theme_config:
  date_format: "%Y-%m-%d"
  back_home_text: ".."
