highlighter: rouge
markdown: kramdown
remote_theme: riggraz/no-style-please
name: gweezlebur.com
description: Internet home of Michael D. Ivey since '99
url: https://gweezlebur.com
collections:
  notes:
    output: true
    permalink: notes/:year/:month/:day/:hour:minute:second
